config/routes.rb
Rails.application.routes.draw do

  get "/articles/again_new" => "articles#mynew", as: :my_n_article
  post "/articles/again_create" => "articles#mycreate", as: :my_c_article
  get "/articles/again_edit/:dke"  => "articles#myedit", as: :my_e_article
  get "/articles/again/:dks" => "articles#myshow", as: :my_s_article
  get "/articles/again_index" => "articles#myindex", as: :my_i_article
  patch "/articles/again_upd/:dku"  => "articles#myupd", as: :my_u_article
  delete "articles/again_del/:dkd" => "articles#mydel", as: :my_d_article

  #get "/gaurs/new"	=> "gaurs#new", as: :gaur_new
  #resources :gaurs

  get 'dk/index'
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dk#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def mynew
		#new keyword for creating new object
		@article = Article.new
	end

	def myindex
		@myallarticle = Article.all
	end

	def mycreate
       @article = Article.new(hello_hiiii)
		 
		  if @article.save
		  redirect_to my_s_article_path(@article)
		  else
		  	render 'mynew'
		  end
	end

	def myedit
	  @article11 = Article.find(params[:dke])
	end

	def myshow
		@article = Article.find(params[:dks])
	end

	def myupd
	  @article11 = Article.find(params[:dku])
	 
	  if @article11.update(hello_hiiii)
	    redirect_to my_i_article_path
	  else
	    render 'myedit'
	  end
	end

	def mydel
	  @article11 = Article.find(params[:dkd])
	  @article11.destroy	 
	  redirect_to my_i_article_path
	end



	private

	def hello_hiiii
		params.require(:myallarticle).permit(:title, :text)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/dk_controller.rb
class DkController < ApplicationController
  def index
  end

end

app/controllers/gaurs_controller.rb
class GaursController < ApplicationController
	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dk_helper.rb
module DkHelper
end

app/views/articles/myedit.html.erb
<h1>Edit article</h1>
 <%= form_with model: @article11, scope: :myallarticle, url: my_u_article_path(@article11), local: true do |form| %>

 <% if @article11.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article11.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article11.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
    <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<p>
  <strong>Title:</strong>
  <%= @article11.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article11.text %>
</p>

app/views/articles/myindex.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @myallarticle.each do |ar| %>
    <tr>
      <td><%= ar.title %></td>
      <td><%= ar.text %></td>
      <td><%= link_to 'Show', my_s_article_path(ar) %></td>
      <td><%= link_to 'Edit', my_e_article_path(ar) %></td>
      <td><%= link_to 'Delete', my_d_article_path(ar) ,
              method: :delete,
              data: { confirm: 'Are you sure?'} %></td>

    </tr>
  <% end %>
</table>

app/views/articles/mynew.html.erb
<h1>This is form for New Article</h1>
<h1>this is form page</h1>


<%= form_with model: @article, scope: :myallarticle, url: my_c_article_path, local: true do |form| %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/myshow.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/dk/index.html.erb
<h1>Hellow rails in index!</h1>

<h2><%= link_to 'all article', my_i_article_path %></h2>
<h2><%= link_to 'new article', my_n_article_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>